name: app1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  provider: ^6.0.0
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 添加 assets 配置

  assets:
    - assets/hanzi_writer.html
    - assets/challenge_writer.html
    - assets/words.json
    - assets/cat.png
    - assets/hole.png


  # 如果有其他資產文件（例如圖片、字體等），也可以在這裡添加，例如：
  # assets:
  #   - assets/hanzi_writer.html
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 如果需要自定義字體，可以取消註釋以下部分並根據需求修改
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700