// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqa12EFnLttTxIysELN_rv945ueYP2raY',
    appId: '1:645113443642:web:f2f96384b6a37118690c03',
    messagingSenderId: '645113443642',
    projectId: 'handwritten-f4251',
    authDomain: 'handwritten-f4251.firebaseapp.com',
    storageBucket: 'handwritten-f4251.firebasestorage.app',
    measurementId: 'G-1WGW2Q9C2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9-aE_WguF-HwxnPNmeAt3O9M8_ckkZs',
    appId: '1:645113443642:android:debe307c7c7a2244690c03',
    messagingSenderId: '645113443642',
    projectId: 'handwritten-f4251',
    storageBucket: 'handwritten-f4251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOOgeqzl5JMbr0E3VV49BZho7dcWqKPQ',
    appId: '1:645113443642:ios:05f65cb6d0ec3ada690c03',
    messagingSenderId: '645113443642',
    projectId: 'handwritten-f4251',
    storageBucket: 'handwritten-f4251.firebasestorage.app',
    iosClientId: '645113443642-4s7gu5snks9aad4uqqep8831jl653mot.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOOgeqzl5JMbr0E3VV49BZho7dcWqKPQ',
    appId: '1:645113443642:ios:05f65cb6d0ec3ada690c03',
    messagingSenderId: '645113443642',
    projectId: 'handwritten-f4251',
    storageBucket: 'handwritten-f4251.firebasestorage.app',
    iosClientId: '645113443642-4s7gu5snks9aad4uqqep8831jl653mot.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqa12EFnLttTxIysELN_rv945ueYP2raY',
    appId: '1:645113443642:web:a7a05e7212770534690c03',
    messagingSenderId: '645113443642',
    projectId: 'handwritten-f4251',
    authDomain: 'handwritten-f4251.firebaseapp.com',
    storageBucket: 'handwritten-f4251.firebasestorage.app',
    measurementId: 'G-CFC1E6V750',
  );

}